version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: weather-postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: